name: Ned Walker
favicon: null
layout_spectrum: 0.57091
typography_spectrum: 0.9512563936877996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0909'
    - '#ffffff'
    - '#c0884d'
    - '#ff3731'
    - '#1effce'
  brandStrength: 0.3344883914105594
  lightness: 0.13703041151165962
  saturation: 0.722367413341999
  rhythmicContrast: 0.6411812729202211
purpose: []
